### ISSUE TITLE
Incorrect number of bindings supplied

### ISSUE THREAD

**Issue by gema-arta** [dotslash/recent2#31]
https://github.com/dotslash/recent2/blob/3f14633736f9cde0f9d1a9bcd704b044c79a01f0/recent2.py#L284

```
Traceback (most recent call last):
  File "/usr/local/bin/recent-import-bash-history", line 8, in <module>
    sys.exit(import_bash_history_entry_point())
  File "/usr/local/lib/python3.8/site-packages/recent2.py", line 228, in import_bash_history_entry_point
    import_bash_history()
  File "/usr/local/lib/python3.8/site-packages/recent2.py", line 280, in import_bash_history
    c.execute(SQL.INSERT_ROW_CUSTOM_TS, [
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 6, and there are 7 supplied.
```

```
Python 3.8.2 (default, Feb 28 2020, 00:00:00)
[GCC 10.0.1 20200216 (Red Hat 10.0.1-0.8)] on linux

Distributor ID: Fedora
Description:    Fedora release 32 (Thirty Two)
Release:        32
Codename:       ThirtyTwo
```
workaround 

```
            # exit status=-1, working directory=/unknown
            -1, "/unknown",
            session.id,])
    conn.commit()
    conn.close()
```

**Comment by dotslash** [comment]
Oops. This is bad. I will fix this in the next 1 week.

Thanks for reaching out
